Repository Waishnav/Watcher, pull requests merged in 2022-10, with the labels that each got.

#22 fix: shebang line updated calling pyhton3 interepreter instead of python
  README.md
  src/bin/watcher
Labels: enhancement, hactoberfest-accepted

#23 Added CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: hactoberfest-accepted

#25 Fix: shorten the app-name in watcher -ds result
  CONTRIBUTING.md
  README.md
  src/Watcher/commands.py
  src/bin/watcher
Labels: enhancement, hactoberfest-accepted

#35 fix: Change directory from 'raw_data' to 'daily_data'
  install
Labels: hacktoberfest-accepted

#34 fix : v2.0 Issue to avoid replication of data as day changed
  src/Watcher/watch_log.py
Labels: hacktoberfest-accepted
